-- MySQL Script generated by MySQL Workbench
-- Wed Nov 15 12:36:06 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema SAS
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `SAS` ;

-- -----------------------------------------------------
-- Schema SAS
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SAS` DEFAULT CHARACTER SET utf8 ;
USE `SAS` ;

-- -----------------------------------------------------
-- Table `SAS`.`Categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SAS`.`Categories` ;

CREATE TABLE IF NOT EXISTS `SAS`.`Categories` (
  `categoryId` INT NOT NULL AUTO_INCREMENT,
  `categoryName` VARCHAR(50) NOT NULL DEFAULT 'ทั่วไป',
  PRIMARY KEY (`categoryId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SAS`.`Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SAS`.`Users` ;

CREATE TABLE IF NOT EXISTS `SAS`.`Users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  `role` ENUM('admin', 'announcer') NOT NULL DEFAULT 'announcer',
  `createdOn` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedOn` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
   CHARACTER SET utf8 COLLATE utf8_bin
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SAS`.`Announcements`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SAS`.`Announcements` ;

CREATE TABLE IF NOT EXISTS `SAS`.`Announcements` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `announcementTitle` VARCHAR(200) NOT NULL,
  `announcementDescription` VARCHAR(10000) NOT NULL,
  `publishDate` DATETIME NULL,
  `closeDate` DATETIME NULL,
  `announcementDisplay` ENUM('Y', 'N') NOT NULL DEFAULT 'N',
  `categoryId` INT NOT NULL,
  `viewCount` INT NOT NULL DEFAULT 0,
  `announcementOwner` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Announcements_Categories_idx` (`categoryId` ASC) VISIBLE,
  INDEX `fk_Announcements_Users1_idx` (`announcementOwner` ASC) VISIBLE,
  CONSTRAINT `fk_Announcements_Categories`
    FOREIGN KEY (`categoryId`)
    REFERENCES `SAS`.`Categories` (`categoryId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Announcements_Users1`
    FOREIGN KEY (`announcementOwner`)
    REFERENCES `SAS`.`Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SAS`.`Subscriptions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SAS`.`Subscriptions` ;

CREATE TABLE IF NOT EXISTS `SAS`.`Subscriptions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `subscriberEmail` VARCHAR(150) NOT NULL,
  `createdOn` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedOn` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `categoryId` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Subscribes_Categories1_idx` (`categoryId` ASC) VISIBLE,
  CONSTRAINT `fk_Subscribes_Categories1`
    FOREIGN KEY (`categoryId`)
    REFERENCES `SAS`.`Categories` (`categoryId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
