services:
  reverse-proxy:
    image: nginx:latest
    container_name: nginx-reverse-proxy
    volumes:
      - ./reverse-proxy.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl/dhparam-2048.pem:/ssl/dhparam-2048.pem
      - ./nginx/ssl/fullchain.pem:/ssl/fullchain.pem
      - ./nginx/ssl/privkey.pem:/ssl/privkey.pem 
    ports:
      - "80:80"
      - "443:443"
    networks:
      - proxy
    restart: always
  front:
    image: front1
    container_name: front
    build: 
      context: ./nw1-sas-frontend/
      dockerfile: FrontDockerfile
    ports:
      - "80"
    networks:
      - proxy
  back:
    image: openjdk:17-jdk-alpine
    container_name: back
    working_dir: /app
    command: sh -c "java -jar *.jar"
    ports:
      - "8080"
    restart: on-failure
    depends_on: 
      - dbserver
    volumes:
      - ./nw1-api-sas/target:/app
    environment:
      - mysql_user=chowder1
      - mysql_password=nw1@chowder
      - mysql_url=dbserver
    networks:
      - dbnet
      - proxy
  dbserver:
    image: mysql:8.0.33
    container_name: db-container
    volumes:
    #  - ./nw1-sas-db:/docker-entrypoint-initdb.d
      - ./database:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=nw1@chowder
      - MYSQL_USER=chowder1
      - MYSQL_PASSWORD=nw1@chowder
      - MYSQL_DATABASE=SAS
      - LANG="en_US.UTF-8"
    networks:
      - dbnet
   # restart: on-failure
networks:
  dbnet:
  proxy:
